/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;

/**
 *
 * @author user
 */
public class CarritoOfer_Item extends javax.swing.JPanel {

    /**
     * Creates new form CarritoOfer_Item
     */
    public CarritoOfer_Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ofer_Circulo1 = new Componentes.Ofer_Circulo();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(50, 50));
        setLayout(null);
        add(ofer_Circulo1);
        ofer_Circulo1.setBounds(20, 30, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-shopping-cart-48.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 70, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private Componentes.Ofer_Circulo ofer_Circulo1;
    // End of variables declaration//GEN-END:variables
}
