/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista_Orden;

/**
 *
 * @author user
 */
public class CarritoCompra extends javax.swing.JPanel {

    /**
     * Creates new form CarritoCompra
     */
    public CarritoCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelCentrar = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout panelCentrarLayout = new javax.swing.GroupLayout(panelCentrar);
        panelCentrar.setLayout(panelCentrarLayout);
        panelCentrarLayout.setHorizontalGroup(
            panelCentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelCentrarLayout.setVerticalGroup(
            panelCentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelCentrar);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelInferior.setPreferredSize(new java.awt.Dimension(400, 40));
        panelInferior.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Subtotal");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 16));
        panelInferior.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setText("######");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 16));
        panelInferior.add(jLabel2, java.awt.BorderLayout.LINE_END);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCentrar;
    private javax.swing.JPanel panelInferior;
    // End of variables declaration//GEN-END:variables
}
