/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Usuario;
import Persistencia.UsuarioDAO;
import java.io.File;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 *
 * @author user
 */
public class Vista_EnvioCorreo extends javax.swing.JFrame {

    private String emailFrom = "inkafashion.soporte@gmail.com";
    private String password = "vryj dssh aczn kemq";
    private String mailTo;
    private String subject;
    private String conten;
    private Authenticator auth;
    private File[] file;
    private Properties properties;
    
    public Vista_EnvioCorreo() {
        initComponents();
        this.setLocationRelativeTo(null);
        properties = new Properties();
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        properties.setProperty("mail.smtp.starttls.enable", "true");
        properties.setProperty("mail.smtp.port", "587");
        properties.setProperty("mail.smtp.user", emailFrom);
        properties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
        properties.setProperty("mail.smtp.auth", "true");
        
        auth = new Authenticator() {
            public PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(emailFrom,password);
            }
        };
    }
    
    private void CrearCorreo(){
        mailTo = txt_correo.getText().trim();
        subject = "Reestablecimiento de Contraseña";
        UsuarioDAO usuarioDAO = new UsuarioDAO(); 
        Usuario usuario = usuarioDAO.obtenerUsuarioPorCorreo(mailTo);
        
        conten = "<html>"
            + "<body>"
            + "<h2>Hola " + usuario.getNombre() + " " + usuario.getApellido() + ",</h2>"
            + "<p>Has solicitado restablecer tu contraseña. Aquí están tus datos:</p>"
            + "<ul>"
            + "<li><b>Usuario:</b> " + usuario.getUsuario() + "</li>"
            + "<li><b>Contraseña:</b> <span style='color:red;'>" + usuario.getClave() + "</span></li>"
            + "</ul>"
            + "<p>Por favor, mantén esta información segura.</p>"
            + "<p>Atentamente,<br>Equipo de Soporte</p>"
            + "</body>"
            + "</html>";
        
        Session mSession = Session.getInstance(properties, auth);
        
        Message msg = new MimeMessage(mSession);
        try {
            msg.setFrom(new InternetAddress(emailFrom));
            InternetAddress[] toAddresses = 
            {new InternetAddress(mailTo)};
            msg.setRecipients(Message.RecipientType.TO, toAddresses);
            msg.setSubject(subject);
            msg.setSentDate(new java.util.Date());
            MimeBodyPart mimeBodyPart = new MimeBodyPart();
            mimeBodyPart.setContent(conten, "text/html");
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(mimeBodyPart);
            
            msg.setContent(multipart);
            Transport.send(msg);
            raven.toast.Notifications.getInstance().show(raven.toast.Notifications.Type.SUCCESS, "Correo enviado exitosamente.");
        } catch (Exception e) {
            raven.toast.Notifications.getInstance().show(raven.toast.Notifications.Type.ERROR, "Error al enviar correo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Correo Electronico:");

        txt_correo.putClientProperty("JTextField.placeholderText", "Ingrese su correo electronico");
        txt_correo.putClientProperty( "JComponent.roundRect" , true );

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_correo))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton1)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UsuarioDAO usuarioDAO = new UsuarioDAO(); // Instancia de la clase UsuarioDAO

        // Validación del correo
        if (!usuarioDAO.ValidarFormatoCorreo(txt_correo, "correo electrónico")) {
        // Si no pasa la validación, el mensaje de error ya se muestra en la notificación
            return;
        }
        // Si pasa la validación
        raven.toast.Notifications.getInstance().show(raven.toast.Notifications.Type.SUCCESS, "El correo electrónico es válido. Enviando datos...");
        // Aquí añades tu lógica para enviar datosx
        CrearCorreo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_EnvioCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_EnvioCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration//GEN-END:variables
}
